'use strict';
angular.module('starlab.services', [])
    .constant('baseURL', '/')
    .factory('biradFactory', ['$resource', 'baseURL', function($resource, baseURL) {
        var biradFac = {};
        biradFac.getChartObject = function() {
            return $resource(baseURL + 'birad/dataset1');
        };
        return biradFac;
    }])
    .factory('birdFactory', [function() {
        var birdFac = {};
        //have to move the code to the backend later
        birdFac.graph = [{
            nodes: [{
                "class": 1
            }, {
                "class": 2
            }, {
                "class": 2
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 3
            }, {
                "class": 3
            }, {
                "class": 3
            }, {
                "class": 3
            }, {
                "class": 3
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }],
            links: [{
                "similarity": 0.099602,
                "source": 0,
                "target": 16
            }, {
                "similarity": 0.099396,
                "source": 0,
                "target": 67
            }, {
                "similarity": 0.099767,
                "source": 1,
                "target": 74
            }, {
                "similarity": 0.099922,
                "source": 1,
                "target": 87
            }, {
                "similarity": 0.099974,
                "source": 2,
                "target": 6
            }, {
                "similarity": 0.099679,
                "source": 3,
                "target": 29
            }, {
                "similarity": 0.099512,
                "source": 4,
                "target": 12
            }, {
                "similarity": 0.099147,
                "source": 4,
                "target": 34
            }, {
                "similarity": 0.099326,
                "source": 4,
                "target": 62
            }, {
                "similarity": 0.099153,
                "source": 4,
                "target": 94
            }, {
                "similarity": 0.099029,
                "source": 6,
                "target": 67
            }, {
                "similarity": 0.099712,
                "source": 6,
                "target": 78
            }, {
                "similarity": 0.099997,
                "source": 7,
                "target": 50
            }, {
                "similarity": 0.099937,
                "source": 9,
                "target": 42
            }, {
                "similarity": 0.099428,
                "source": 10,
                "target": 34
            }, {
                "similarity": 0.099072,
                "source": 12,
                "target": 29
            }, {
                "similarity": 0.09984,
                "source": 12,
                "target": 70
            }, {
                "similarity": 0.099204,
                "source": 13,
                "target": 80
            }, {
                "similarity": 0.19311,
                "source": 15,
                "target": 16
            }, {
                "similarity": 0.19244,
                "source": 15,
                "target": 17
            }, {
                "similarity": 0.1994,
                "source": 15,
                "target": 18
            }, {
                "similarity": 0.1994,
                "source": 15,
                "target": 19
            }, {
                "similarity": 0.19343,
                "source": 16,
                "target": 17
            }, {
                "similarity": 0.19869,
                "source": 16,
                "target": 18
            }, {
                "similarity": 0.19869,
                "source": 16,
                "target": 19
            }, {
                "similarity": 0.099129,
                "source": 16,
                "target": 43
            }, {
                "similarity": 0.099465,
                "source": 16,
                "target": 53
            }, {
                "similarity": 0.099483,
                "source": 16,
                "target": 91
            }, {
                "similarity": 0.099739,
                "source": 16,
                "target": 92
            }, {
                "similarity": 0.1993,
                "source": 17,
                "target": 18
            }, {
                "similarity": 0.1993,
                "source": 17,
                "target": 19
            }, {
                "similarity": 0.099755,
                "source": 17,
                "target": 26
            }, {
                "similarity": 0.19244,
                "source": 18,
                "target": 19
            }, {
                "similarity": 0.099712,
                "source": 18,
                "target": 22
            }, {
                "similarity": 0.099799,
                "source": 18,
                "target": 23
            }, {
                "similarity": 0.099946,
                "source": 19,
                "target": 47
            }, {
                "similarity": 0.099708,
                "source": 19,
                "target": 60
            }, {
                "similarity": 0.099415,
                "source": 22,
                "target": 84
            }, {
                "similarity": 0.099844,
                "source": 23,
                "target": 45
            }, {
                "similarity": 0.09922,
                "source": 25,
                "target": 43
            }, {
                "similarity": 0.099659,
                "source": 25,
                "target": 66
            }, {
                "similarity": 0.099455,
                "source": 25,
                "target": 81
            }, {
                "similarity": 0.099127,
                "source": 26,
                "target": 67
            }, {
                "similarity": 0.099345,
                "source": 28,
                "target": 85
            }, {
                "similarity": 0.099308,
                "source": 30,
                "target": 49
            }, {
                "similarity": 0.099416,
                "source": 31,
                "target": 88
            }, {
                "similarity": 0.099997,
                "source": 32,
                "target": 95
            }, {
                "similarity": 0.099631,
                "source": 33,
                "target": 86
            }, {
                "similarity": 0.099195,
                "source": 34,
                "target": 78
            }, {
                "similarity": 0.099142,
                "source": 34,
                "target": 93
            }, {
                "similarity": 0.099602,
                "source": 37,
                "target": 48
            }, {
                "similarity": 0.099131,
                "source": 37,
                "target": 68
            }, {
                "similarity": 0.099496,
                "source": 37,
                "target": 91
            }, {
                "similarity": 0.099523,
                "source": 38,
                "target": 80
            }, {
                "similarity": 0.099362,
                "source": 41,
                "target": 57
            }, {
                "similarity": 0.099088,
                "source": 41,
                "target": 59
            }, {
                "similarity": 0.099957,
                "source": 44,
                "target": 85
            }, {
                "similarity": 0.099116,
                "source": 45,
                "target": 64
            }, {
                "similarity": 0.09955,
                "source": 46,
                "target": 63
            }, {
                "similarity": 0.099726,
                "source": 46,
                "target": 95
            }, {
                "similarity": 0.099917,
                "source": 47,
                "target": 68
            }, {
                "similarity": 0.099418,
                "source": 50,
                "target": 98
            }, {
                "similarity": 0.099814,
                "source": 51,
                "target": 70
            }, {
                "similarity": 0.099016,
                "source": 54,
                "target": 92
            }, {
                "similarity": 0.099073,
                "source": 55,
                "target": 94
            }, {
                "similarity": 0.099098,
                "source": 56,
                "target": 82
            }, {
                "similarity": 0.099024,
                "source": 58,
                "target": 97
            }, {
                "similarity": 0.09994,
                "source": 60,
                "target": 69
            }, {
                "similarity": 0.099772,
                "source": 61,
                "target": 76
            }, {
                "similarity": 0.099971,
                "source": 64,
                "target": 69
            }, {
                "similarity": 0.099932,
                "source": 69,
                "target": 96
            }, {
                "similarity": 0.099156,
                "source": 72,
                "target": 99
            }, {
                "similarity": 0.099817,
                "source": 73,
                "target": 87
            }, {
                "similarity": 0.099447,
                "source": 75,
                "target": 93
            }]
        }, {
            nodes: [{
                "class": 1
            }, {
                "class": 2
            }, {
                "class": 2
            }, {
                "class": 2
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 3
            }, {
                "class": 3
            }, {
                "class": 3
            }, {
                "class": 3
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }],
            links: [{
                "similarity": 0.099602,
                "source": 0,
                "target": 16
            }, {
                "similarity": 0.099396,
                "source": 0,
                "target": 67
            }, {
                "similarity": 0.099767,
                "source": 1,
                "target": 74
            }, {
                "similarity": 0.099922,
                "source": 1,
                "target": 87
            }, {
                "similarity": 0.099974,
                "source": 2,
                "target": 6
            }, {
                "similarity": 0.099679,
                "source": 3,
                "target": 29
            }, {
                "similarity": 0.099512,
                "source": 4,
                "target": 12
            }, {
                "similarity": 0.099147,
                "source": 4,
                "target": 34
            }, {
                "similarity": 0.099326,
                "source": 4,
                "target": 62
            }, {
                "similarity": 0.099153,
                "source": 4,
                "target": 94
            }, {
                "similarity": 0.099029,
                "source": 6,
                "target": 67
            }, {
                "similarity": 0.099712,
                "source": 6,
                "target": 78
            }, {
                "similarity": 0.099997,
                "source": 7,
                "target": 50
            }, {
                "similarity": 0.099937,
                "source": 9,
                "target": 42
            }, {
                "similarity": 0.099428,
                "source": 10,
                "target": 34
            }, {
                "similarity": 0.099072,
                "source": 12,
                "target": 29
            }, {
                "similarity": 0.09984,
                "source": 12,
                "target": 70
            }, {
                "similarity": 0.099204,
                "source": 13,
                "target": 80
            }, {
                "similarity": 0.19343,
                "source": 16,
                "target": 17
            }, {
                "similarity": 0.19869,
                "source": 16,
                "target": 18
            }, {
                "similarity": 0.19869,
                "source": 16,
                "target": 19
            }, {
                "similarity": 0.099129,
                "source": 16,
                "target": 43
            }, {
                "similarity": 0.099465,
                "source": 16,
                "target": 53
            }, {
                "similarity": 0.099483,
                "source": 16,
                "target": 91
            }, {
                "similarity": 0.099739,
                "source": 16,
                "target": 92
            }, {
                "similarity": 0.1993,
                "source": 17,
                "target": 18
            }, {
                "similarity": 0.1993,
                "source": 17,
                "target": 19
            }, {
                "similarity": 0.099755,
                "source": 17,
                "target": 26
            }, {
                "similarity": 0.19244,
                "source": 18,
                "target": 19
            }, {
                "similarity": 0.099712,
                "source": 18,
                "target": 22
            }, {
                "similarity": 0.099799,
                "source": 18,
                "target": 23
            }, {
                "similarity": 0.099946,
                "source": 19,
                "target": 47
            }, {
                "similarity": 0.099708,
                "source": 19,
                "target": 60
            }, {
                "similarity": 0.099415,
                "source": 22,
                "target": 84
            }, {
                "similarity": 0.099844,
                "source": 23,
                "target": 45
            }, {
                "similarity": 0.09922,
                "source": 25,
                "target": 43
            }, {
                "similarity": 0.099659,
                "source": 25,
                "target": 66
            }, {
                "similarity": 0.099455,
                "source": 25,
                "target": 81
            }, {
                "similarity": 0.099127,
                "source": 26,
                "target": 67
            }, {
                "similarity": 0.099345,
                "source": 28,
                "target": 85
            }, {
                "similarity": 0.099308,
                "source": 30,
                "target": 49
            }, {
                "similarity": 0.099416,
                "source": 31,
                "target": 88
            }, {
                "similarity": 0.099997,
                "source": 32,
                "target": 95
            }, {
                "similarity": 0.099631,
                "source": 33,
                "target": 86
            }, {
                "similarity": 0.099195,
                "source": 34,
                "target": 78
            }, {
                "similarity": 0.099142,
                "source": 34,
                "target": 93
            }, {
                "similarity": 0.099602,
                "source": 37,
                "target": 48
            }, {
                "similarity": 0.099131,
                "source": 37,
                "target": 68
            }, {
                "similarity": 0.099496,
                "source": 37,
                "target": 91
            }, {
                "similarity": 0.099523,
                "source": 38,
                "target": 80
            }, {
                "similarity": 0.099362,
                "source": 41,
                "target": 57
            }, {
                "similarity": 0.099088,
                "source": 41,
                "target": 59
            }, {
                "similarity": 0.099957,
                "source": 44,
                "target": 85
            }, {
                "similarity": 0.099116,
                "source": 45,
                "target": 64
            }, {
                "similarity": 0.09955,
                "source": 46,
                "target": 63
            }, {
                "similarity": 0.099726,
                "source": 46,
                "target": 95
            }, {
                "similarity": 0.099917,
                "source": 47,
                "target": 68
            }, {
                "similarity": 0.099418,
                "source": 50,
                "target": 98
            }, {
                "similarity": 0.099814,
                "source": 51,
                "target": 70
            }, {
                "similarity": 0.099016,
                "source": 54,
                "target": 92
            }, {
                "similarity": 0.099073,
                "source": 55,
                "target": 94
            }, {
                "similarity": 0.099098,
                "source": 56,
                "target": 82
            }, {
                "similarity": 0.099024,
                "source": 58,
                "target": 97
            }, {
                "similarity": 0.09994,
                "source": 60,
                "target": 69
            }, {
                "similarity": 0.099772,
                "source": 61,
                "target": 76
            }, {
                "similarity": 0.099971,
                "source": 64,
                "target": 69
            }, {
                "similarity": 0.099932,
                "source": 69,
                "target": 96
            }, {
                "similarity": 0.099156,
                "source": 72,
                "target": 99
            }, {
                "similarity": 0.099817,
                "source": 73,
                "target": 87
            }, {
                "similarity": 0.099447,
                "source": 75,
                "target": 93
            }]
        }, {
            nodes: [{
                "class": 1
            }, {
                "class": 2
            }, {
                "class": 2
            }, {
                "class": 2
            }, {
                "class": 2
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 3
            }, {
                "class": 3
            }, {
                "class": 3
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }],
            links: [{
                "similarity": 0.099602,
                "source": 0,
                "target": 16
            }, {
                "similarity": 0.099396,
                "source": 0,
                "target": 67
            }, {
                "similarity": 0.099303,
                "source": 1,
                "target": 4
            }, {
                "similarity": 0.099767,
                "source": 1,
                "target": 74
            }, {
                "similarity": 0.099922,
                "source": 1,
                "target": 87
            }, {
                "similarity": 0.099974,
                "source": 2,
                "target": 6
            }, {
                "similarity": 0.099679,
                "source": 3,
                "target": 29
            }, {
                "similarity": 0.099512,
                "source": 4,
                "target": 12
            }, {
                "similarity": 0.099147,
                "source": 4,
                "target": 34
            }, {
                "similarity": 0.099326,
                "source": 4,
                "target": 62
            }, {
                "similarity": 0.099153,
                "source": 4,
                "target": 94
            }, {
                "similarity": 0.099029,
                "source": 6,
                "target": 67
            }, {
                "similarity": 0.099712,
                "source": 6,
                "target": 78
            }, {
                "similarity": 0.099997,
                "source": 7,
                "target": 50
            }, {
                "similarity": 0.099937,
                "source": 9,
                "target": 42
            }, {
                "similarity": 0.099428,
                "source": 10,
                "target": 34
            }, {
                "similarity": 0.099072,
                "source": 12,
                "target": 29
            }, {
                "similarity": 0.09984,
                "source": 12,
                "target": 70
            }, {
                "similarity": 0.099204,
                "source": 13,
                "target": 80
            }, {
                "similarity": 0.099129,
                "source": 16,
                "target": 43
            }, {
                "similarity": 0.099465,
                "source": 16,
                "target": 53
            }, {
                "similarity": 0.099483,
                "source": 16,
                "target": 91
            }, {
                "similarity": 0.099739,
                "source": 16,
                "target": 92
            }, {
                "similarity": 0.1993,
                "source": 17,
                "target": 18
            }, {
                "similarity": 0.1993,
                "source": 17,
                "target": 19
            }, {
                "similarity": 0.099755,
                "source": 17,
                "target": 26
            }, {
                "similarity": 0.19244,
                "source": 18,
                "target": 19
            }, {
                "similarity": 0.099712,
                "source": 18,
                "target": 22
            }, {
                "similarity": 0.099799,
                "source": 18,
                "target": 23
            }, {
                "similarity": 0.099946,
                "source": 19,
                "target": 47
            }, {
                "similarity": 0.099708,
                "source": 19,
                "target": 60
            }, {
                "similarity": 0.099415,
                "source": 22,
                "target": 84
            }, {
                "similarity": 0.099844,
                "source": 23,
                "target": 45
            }, {
                "similarity": 0.09922,
                "source": 25,
                "target": 43
            }, {
                "similarity": 0.099659,
                "source": 25,
                "target": 66
            }, {
                "similarity": 0.099455,
                "source": 25,
                "target": 81
            }, {
                "similarity": 0.099127,
                "source": 26,
                "target": 67
            }, {
                "similarity": 0.099345,
                "source": 28,
                "target": 85
            }, {
                "similarity": 0.099308,
                "source": 30,
                "target": 49
            }, {
                "similarity": 0.099416,
                "source": 31,
                "target": 88
            }, {
                "similarity": 0.099997,
                "source": 32,
                "target": 95
            }, {
                "similarity": 0.099631,
                "source": 33,
                "target": 86
            }, {
                "similarity": 0.099195,
                "source": 34,
                "target": 78
            }, {
                "similarity": 0.099142,
                "source": 34,
                "target": 93
            }, {
                "similarity": 0.099602,
                "source": 37,
                "target": 48
            }, {
                "similarity": 0.099131,
                "source": 37,
                "target": 68
            }, {
                "similarity": 0.099496,
                "source": 37,
                "target": 91
            }, {
                "similarity": 0.099523,
                "source": 38,
                "target": 80
            }, {
                "similarity": 0.099362,
                "source": 41,
                "target": 57
            }, {
                "similarity": 0.099088,
                "source": 41,
                "target": 59
            }, {
                "similarity": 0.099957,
                "source": 44,
                "target": 85
            }, {
                "similarity": 0.099116,
                "source": 45,
                "target": 64
            }, {
                "similarity": 0.09955,
                "source": 46,
                "target": 63
            }, {
                "similarity": 0.099726,
                "source": 46,
                "target": 95
            }, {
                "similarity": 0.099917,
                "source": 47,
                "target": 68
            }, {
                "similarity": 0.099418,
                "source": 50,
                "target": 98
            }, {
                "similarity": 0.099814,
                "source": 51,
                "target": 70
            }, {
                "similarity": 0.099016,
                "source": 54,
                "target": 92
            }, {
                "similarity": 0.099073,
                "source": 55,
                "target": 94
            }, {
                "similarity": 0.099098,
                "source": 56,
                "target": 82
            }, {
                "similarity": 0.099024,
                "source": 58,
                "target": 97
            }, {
                "similarity": 0.09994,
                "source": 60,
                "target": 69
            }, {
                "similarity": 0.099772,
                "source": 61,
                "target": 76
            }, {
                "similarity": 0.099971,
                "source": 64,
                "target": 69
            }, {
                "similarity": 0.099932,
                "source": 69,
                "target": 96
            }, {
                "similarity": 0.099156,
                "source": 72,
                "target": 99
            }, {
                "similarity": 0.099817,
                "source": 73,
                "target": 87
            }, {
                "similarity": 0.099447,
                "source": 75,
                "target": 93
            }]
        }, {
            nodes: [{
                "class": 1
            }, {
                "class": 2
            }, {
                "class": 2
            }, {
                "class": 2
            }, {
                "class": 2
            }, {
                "class": 2
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 3
            }, {
                "class": 3
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }],
            links: [{
                "similarity": 0.099602,
                "source": 0,
                "target": 16
            }, {
                "similarity": 0.099396,
                "source": 0,
                "target": 67
            }, {
                "similarity": 0.099303,
                "source": 1,
                "target": 4
            }, {
                "similarity": 0.099767,
                "source": 1,
                "target": 74
            }, {
                "similarity": 0.099922,
                "source": 1,
                "target": 87
            }, {
                "similarity": 0.099403,
                "source": 2,
                "target": 5
            }, {
                "similarity": 0.099974,
                "source": 2,
                "target": 6
            }, {
                "similarity": 0.099679,
                "source": 3,
                "target": 29
            }, {
                "similarity": 0.099302,
                "source": 4,
                "target": 5
            }, {
                "similarity": 0.099512,
                "source": 4,
                "target": 12
            }, {
                "similarity": 0.099147,
                "source": 4,
                "target": 34
            }, {
                "similarity": 0.099326,
                "source": 4,
                "target": 62
            }, {
                "similarity": 0.099153,
                "source": 4,
                "target": 94
            }, {
                "similarity": 0.099029,
                "source": 6,
                "target": 67
            }, {
                "similarity": 0.099712,
                "source": 6,
                "target": 78
            }, {
                "similarity": 0.099997,
                "source": 7,
                "target": 50
            }, {
                "similarity": 0.099937,
                "source": 9,
                "target": 42
            }, {
                "similarity": 0.099428,
                "source": 10,
                "target": 34
            }, {
                "similarity": 0.099072,
                "source": 12,
                "target": 29
            }, {
                "similarity": 0.09984,
                "source": 12,
                "target": 70
            }, {
                "similarity": 0.099204,
                "source": 13,
                "target": 80
            }, {
                "similarity": 0.099129,
                "source": 16,
                "target": 43
            }, {
                "similarity": 0.099465,
                "source": 16,
                "target": 53
            }, {
                "similarity": 0.099483,
                "source": 16,
                "target": 91
            }, {
                "similarity": 0.099739,
                "source": 16,
                "target": 92
            }, {
                "similarity": 0.099755,
                "source": 17,
                "target": 26
            }, {
                "similarity": 0.19244,
                "source": 18,
                "target": 19
            }, {
                "similarity": 0.099712,
                "source": 18,
                "target": 22
            }, {
                "similarity": 0.099799,
                "source": 18,
                "target": 23
            }, {
                "similarity": 0.099946,
                "source": 19,
                "target": 47
            }, {
                "similarity": 0.099708,
                "source": 19,
                "target": 60
            }, {
                "similarity": 0.099415,
                "source": 22,
                "target": 84
            }, {
                "similarity": 0.099844,
                "source": 23,
                "target": 45
            }, {
                "similarity": 0.09922,
                "source": 25,
                "target": 43
            }, {
                "similarity": 0.099659,
                "source": 25,
                "target": 66
            }, {
                "similarity": 0.099455,
                "source": 25,
                "target": 81
            }, {
                "similarity": 0.099127,
                "source": 26,
                "target": 67
            }, {
                "similarity": 0.099345,
                "source": 28,
                "target": 85
            }, {
                "similarity": 0.099308,
                "source": 30,
                "target": 49
            }, {
                "similarity": 0.099416,
                "source": 31,
                "target": 88
            }, {
                "similarity": 0.099997,
                "source": 32,
                "target": 95
            }, {
                "similarity": 0.099631,
                "source": 33,
                "target": 86
            }, {
                "similarity": 0.099195,
                "source": 34,
                "target": 78
            }, {
                "similarity": 0.099142,
                "source": 34,
                "target": 93
            }, {
                "similarity": 0.099602,
                "source": 37,
                "target": 48
            }, {
                "similarity": 0.099131,
                "source": 37,
                "target": 68
            }, {
                "similarity": 0.099496,
                "source": 37,
                "target": 91
            }, {
                "similarity": 0.099523,
                "source": 38,
                "target": 80
            }, {
                "similarity": 0.099362,
                "source": 41,
                "target": 57
            }, {
                "similarity": 0.099088,
                "source": 41,
                "target": 59
            }, {
                "similarity": 0.099957,
                "source": 44,
                "target": 85
            }, {
                "similarity": 0.099116,
                "source": 45,
                "target": 64
            }, {
                "similarity": 0.09955,
                "source": 46,
                "target": 63
            }, {
                "similarity": 0.099726,
                "source": 46,
                "target": 95
            }, {
                "similarity": 0.099917,
                "source": 47,
                "target": 68
            }, {
                "similarity": 0.099418,
                "source": 50,
                "target": 98
            }, {
                "similarity": 0.099814,
                "source": 51,
                "target": 70
            }, {
                "similarity": 0.099016,
                "source": 54,
                "target": 92
            }, {
                "similarity": 0.099073,
                "source": 55,
                "target": 94
            }, {
                "similarity": 0.099098,
                "source": 56,
                "target": 82
            }, {
                "similarity": 0.099024,
                "source": 58,
                "target": 97
            }, {
                "similarity": 0.09994,
                "source": 60,
                "target": 69
            }, {
                "similarity": 0.099772,
                "source": 61,
                "target": 76
            }, {
                "similarity": 0.099971,
                "source": 64,
                "target": 69
            }, {
                "similarity": 0.099932,
                "source": 69,
                "target": 96
            }, {
                "similarity": 0.099156,
                "source": 72,
                "target": 99
            }, {
                "similarity": 0.099817,
                "source": 73,
                "target": 87
            }, {
                "similarity": 0.099447,
                "source": 75,
                "target": 93
            }]
        }, {
            nodes: [{
                "class": 1
            }, {
                "class": 2
            }, {
                "class": 2
            }, {
                "class": 2
            }, {
                "class": 2
            }, {
                "class": 2
            }, {
                "class": 2
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 3
            }, {
                "class": 3
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }, {
                "class": 1
            }],
            links: [{
                "similarity": 0.099602,
                "source": 0,
                "target": 16
            }, {
                "similarity": 0.099396,
                "source": 0,
                "target": 67
            }, {
                "similarity": 0.099303,
                "source": 1,
                "target": 4
            }, {
                "similarity": 0.099767,
                "source": 1,
                "target": 74
            }, {
                "similarity": 0.099922,
                "source": 1,
                "target": 87
            }, {
                "similarity": 0.099403,
                "source": 2,
                "target": 5
            }, {
                "similarity": 0.099403,
                "source": 2,
                "target": 6
            }, {
                "similarity": 0.099679,
                "source": 3,
                "target": 29
            }, {
                "similarity": 0.099302,
                "source": 4,
                "target": 5
            }, {
                "similarity": 0.099302,
                "source": 4,
                "target": 6
            }, {
                "similarity": 0.099512,
                "source": 4,
                "target": 12
            }, {
                "similarity": 0.099147,
                "source": 4,
                "target": 34
            }, {
                "similarity": 0.099326,
                "source": 4,
                "target": 62
            }, {
                "similarity": 0.099153,
                "source": 4,
                "target": 94
            }, {
                "similarity": 0.099029,
                "source": 6,
                "target": 67
            }, {
                "similarity": 0.099712,
                "source": 6,
                "target": 78
            }, {
                "similarity": 0.099997,
                "source": 7,
                "target": 50
            }, {
                "similarity": 0.099937,
                "source": 9,
                "target": 42
            }, {
                "similarity": 0.099428,
                "source": 10,
                "target": 34
            }, {
                "similarity": 0.099072,
                "source": 12,
                "target": 29
            }, {
                "similarity": 0.09984,
                "source": 12,
                "target": 70
            }, {
                "similarity": 0.099204,
                "source": 13,
                "target": 80
            }, {
                "similarity": 0.099129,
                "source": 16,
                "target": 43
            }, {
                "similarity": 0.099465,
                "source": 16,
                "target": 53
            }, {
                "similarity": 0.099483,
                "source": 16,
                "target": 91
            }, {
                "similarity": 0.099739,
                "source": 16,
                "target": 92
            }, {
                "similarity": 0.099755,
                "source": 17,
                "target": 26
            }, {
                "similarity": 0.19244,
                "source": 18,
                "target": 19
            }, {
                "similarity": 0.099712,
                "source": 18,
                "target": 22
            }, {
                "similarity": 0.099799,
                "source": 18,
                "target": 23
            }, {
                "similarity": 0.099946,
                "source": 19,
                "target": 47
            }, {
                "similarity": 0.099708,
                "source": 19,
                "target": 60
            }, {
                "similarity": 0.099415,
                "source": 22,
                "target": 84
            }, {
                "similarity": 0.099844,
                "source": 23,
                "target": 45
            }, {
                "similarity": 0.09922,
                "source": 25,
                "target": 43
            }, {
                "similarity": 0.099659,
                "source": 25,
                "target": 66
            }, {
                "similarity": 0.099455,
                "source": 25,
                "target": 81
            }, {
                "similarity": 0.099127,
                "source": 26,
                "target": 67
            }, {
                "similarity": 0.099345,
                "source": 28,
                "target": 85
            }, {
                "similarity": 0.099308,
                "source": 30,
                "target": 49
            }, {
                "similarity": 0.099416,
                "source": 31,
                "target": 88
            }, {
                "similarity": 0.099997,
                "source": 32,
                "target": 95
            }, {
                "similarity": 0.099631,
                "source": 33,
                "target": 86
            }, {
                "similarity": 0.099195,
                "source": 34,
                "target": 78
            }, {
                "similarity": 0.099142,
                "source": 34,
                "target": 93
            }, {
                "similarity": 0.099602,
                "source": 37,
                "target": 48
            }, {
                "similarity": 0.099131,
                "source": 37,
                "target": 68
            }, {
                "similarity": 0.099496,
                "source": 37,
                "target": 91
            }, {
                "similarity": 0.099523,
                "source": 38,
                "target": 80
            }, {
                "similarity": 0.099362,
                "source": 41,
                "target": 57
            }, {
                "similarity": 0.099088,
                "source": 41,
                "target": 59
            }, {
                "similarity": 0.099957,
                "source": 44,
                "target": 85
            }, {
                "similarity": 0.099116,
                "source": 45,
                "target": 64
            }, {
                "similarity": 0.09955,
                "source": 46,
                "target": 63
            }, {
                "similarity": 0.099726,
                "source": 46,
                "target": 95
            }, {
                "similarity": 0.099917,
                "source": 47,
                "target": 68
            }, {
                "similarity": 0.099418,
                "source": 50,
                "target": 98
            }, {
                "similarity": 0.099814,
                "source": 51,
                "target": 70
            }, {
                "similarity": 0.099016,
                "source": 54,
                "target": 92
            }, {
                "similarity": 0.099073,
                "source": 55,
                "target": 94
            }, {
                "similarity": 0.099098,
                "source": 56,
                "target": 82
            }, {
                "similarity": 0.099024,
                "source": 58,
                "target": 97
            }, {
                "similarity": 0.09994,
                "source": 60,
                "target": 69
            }, {
                "similarity": 0.099772,
                "source": 61,
                "target": 76
            }, {
                "similarity": 0.099971,
                "source": 64,
                "target": 69
            }, {
                "similarity": 0.099932,
                "source": 69,
                "target": 96
            }, {
                "similarity": 0.099156,
                "source": 72,
                "target": 99
            }, {
                "similarity": 0.099817,
                "source": 73,
                "target": 87
            }, {
                "similarity": 0.099447,
                "source": 75,
                "target": 93
            }]
        }];

        return birdFac;
    }]);
